"""
Django settings for incident project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# GDAL_LIBRARY_PATH = r"C:\Program Files\QGIS 3.44.10\bin\gdal312.dll"

# GEOS_LIBRARY_PATH = r"C:\Program Files\QGIS 3.44.10\bin\geos_c.dll"

GDAL_LIBRARY_PATH = r"C:\Program Files\QGIS 3.44.10\bin\gdal312.dll"
GEOS_LIBRARY_PATH = r"C:\Program Files\QGIS 3.44.10\bin\geos_c.dll"

GEOS_LIBRARY_PATH = r"C:\Program Files\PostgreSQL\16\bin\libgeos_c.dll"


# GDAL_LIBRARY_PATH = r"C:\OSGeo4W\bin\gdal310.dll"
# GEOS_LIBRARY_PATH = r"C:\OSGeo4W\bin\geos_c.dll"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", True)

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "daphne",
    "channels",
    "django.contrib.admin",
    "django.contrib.gis",  # Required for GIS fields
    "django.forms",  # Required for TemplatesSetting
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django_cotton",
    "django_htmx",
    "rest_framework",
    "rest_framework_simplejwt",
    "corsheaders",
    "accounts",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "leaflet",
    "reports",  # Contains Incident, State, LGA models (geography + incidents)
    "stations",  # Contains PoliceStation, AmotekunStation (facilities)
    "geography",
    "analytics",
    "dispatch",
    "notifications",
    "chat",
    "surveillance",
    "traffic",
    "mobile",
    "dashboard",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    # Allauth account middleware:
    "allauth.account.middleware.AccountMiddleware",
]

# django-allauth settings
AUTH_USER_MODEL = "dashboard.User"
ACCOUNT_FORMS = {
    'signup': 'dashboard.forms.CustomSignupForm',
}
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

SITE_ID = 1

# # allauth account settings
SIGNUP_FIELDS = ["email*", "username*", "password1*", "password2*"]
LOGIN_METHODS = {"email", "username"}
EMAIL_VERIFICATION = "mandatory"
SESSION_REMEMBER = True

SOCIALACCOUNT_QUERY_EMAIL = True
SOCIALACCOUNT_PROVIDERS = {}


# Tell Django to look in your app templates AND system fallback folders
FORM_RENDERER = "django.forms.renderers.TemplatesSetting"

ROOT_URLCONF = "incident.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    }
]

ASGI_APPLICATION = "incident.asgi.application"
WSGI_APPLICATION = "incident.wsgi.application"

# Django Channels configuration
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                (
                    config("REDIS_HOST", default="127.0.0.1"),
                    int(config("REDIS_PORT", default=6379)),
                )
            ],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


DATABASES = {
    "default": {
        "ENGINE": config("ENGINE"),
        "NAME": config("DB_NAME", default="amotekun_db"),
        "USER": config("DB_USER", default="postgres"),
        "PASSWORD": config("PASSWORD", default=""),
        "HOST": config("DB_HOST", default="localhost"),
        "PORT": config("DB_PORT", default="5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Africa/Lagos"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

LOGIN_REDIRECT_URL = "/dashboard/"
LOGOUT_REDIRECT_URL = "/"

# Celery configuration
CELERY_BROKER_URL = config("CELERY_BROKER_URL", default="redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = config(
    "CELERY_RESULT_BACKEND", default="redis://127.0.0.1:6379/1"
)
CELERY_TIMEZONE = "Africa/Lagos"
CELERY_TASK_ALWAYS_EAGER = False
CELERY_BEAT_SCHEDULE = {
    "collect-traffic-every-15-minutes": {
        "task": "traffic.tasks.collect_traffic_snapshot",
        "schedule": 900.0,
        "options": {"queue": "traffic"},
    },
    "camera-health-check-every-5-minutes": {
        "task": "surveillance.tasks.camera_health_check",
        "schedule": 300.0,
        "options": {"queue": "surveillance"},
    },
}


# REST Framework authentication
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
}

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": config("SECRET_KEY"),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

# Camera credential encryption
CAMERA_ENCRYPTION_KEY = config("CAMERA_ENCRYPTION_KEY", default=config("SECRET_KEY"))

# django-cotton Configuration
COTTON_COMPONENT_DIR = "cotton"
