# Generated by Django 5.2.14 on 2026-07-04 02:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotspotAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(max_length=50)),
                ('parameters', models.JSONField(default=dict)),
                ('hotspot_bounds', django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326)),
                ('results', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('hotspot_type', models.CharField(choices=[('crime', 'Crime'), ('violence', 'Violence'), ('traffic', 'Traffic')], default='crime', max_length=20)),
                ('intensity_score', models.FloatField(help_text='0-1 scale indicating hotspot intensity')),
                ('incident_count', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-intensity_score'],
                'indexes': [models.Index(fields=['hotspot_type', '-intensity_score'], name='analytics_h_hotspot_6f9d90_idx'), models.Index(fields=['-calculated_at'], name='analytics_h_calcula_054391_idx')],
            },
        ),
    ]
