# Generated by Django 6.0 on 2026-07-01 02:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotspot',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='hotspotanalysis',
            name='hotspot_bounds',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddIndex(
            model_name='hotspot',
            index=models.Index(fields=['hotspot_type', '-intensity_score'], name='analytics_h_hotspot_6f9d90_idx'),
        ),
        migrations.AddIndex(
            model_name='hotspot',
            index=models.Index(fields=['-calculated_at'], name='analytics_h_calcula_054391_idx'),
        ),
    ]
