# Generated by Django 6.0 on 2026-06-28 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='assigned_dispatcher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'DISPATCHER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dispatches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='assigned_officer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'OFFICER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_dispatches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='dispatched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='in_progress_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
