# Generated by Django 5.2.14 on 2026-07-09 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0001_initial'),
        ('patrol', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='incident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='reports.incident'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='mission',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_dispatch', to='patrol.patrolmission'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='patrol_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='patrol.patrolteam'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='patrol.vehicle'),
        ),
        migrations.AddField(
            model_name='dispatchhistory',
            name='dispatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='dispatch.dispatch'),
        ),
        migrations.AddField(
            model_name='dispatchhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dispatch',
            index=models.Index(fields=['status'], name='dispatch_di_status_873d01_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatch',
            index=models.Index(fields=['priority'], name='dispatch_di_priorit_335a00_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatch',
            index=models.Index(fields=['state'], name='dispatch_di_state_61c1df_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatch',
            index=models.Index(fields=['lga'], name='dispatch_di_lga_a74fc0_idx'),
        ),
    ]
