# Generated by Django 5.2.14 on 2026-07-09 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='dispatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='dispatch.dispatch'),
        ),
    ]
