# Generated by Django 5.2.14 on 2026-07-09 10:50

import accounts.managers
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('agency_type', models.CharField(choices=[('POLICE', 'Police'), ('AMOTEKUN', 'Amotekun'), ('FRSC', 'Federal Road Safety Corps'), ('NSCDC', 'Nigeria Security and Civil Defence Corps'), ('FIRE', 'Fire Service'), ('LASTMA', 'LASTMA'), ('NEMA', 'NEMA'), ('LASEMA', 'LASEMA'), ('EMS', 'Emergency Medical Service'), ('VOLUNTEER', 'Volunteer'), ('PRIVATE_SECURITY', 'Private Security')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agency/logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=20)),
                ('relationship', models.CharField(max_length=80)),
                ('is_primary', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.BooleanField(default=True)),
                ('sms', models.BooleanField(default=False)),
                ('push', models.BooleanField(default=True)),
                ('in_app', models.BooleanField(default=True)),
                ('incident_updates', models.BooleanField(default=True)),
                ('patrol_updates', models.BooleanField(default=True)),
                ('dispatch_updates', models.BooleanField(default=True)),
                ('security_alerts', models.BooleanField(default=True)),
                ('ai_predictions', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonnelAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('PLATFORM_ADMIN', 'Platform Admin'), ('STATE_COMMANDER', 'State Commander'), ('LGA_COMMANDER', 'LGA Commander'), ('STATION_COMMANDER', 'Station Commander'), ('DISPATCHER', 'Dispatcher'), ('PATROL_SUPERVISOR', 'Patrol Supervisor'), ('PATROL_OFFICER', 'Patrol Officer'), ('RESPONDER', 'Responder'), ('ANALYST', 'Analyst'), ('CCTV_OPERATOR', 'CCTV Operator'), ('EMERGENCY_OPERATOR', 'Emergency Operator'), ('AGENCY_STAFF', 'Agency Staff'), ('CITIZEN', 'Citizen')], max_length=40)),
                ('badge_number', models.CharField(blank=True, max_length=50)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('is_primary', models.BooleanField(default=True)),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON_PATROL', 'On Patrol'), ('ON_DISPATCH', 'On Dispatch'), ('OFF_DUTY', 'Off Duty'), ('LEAVE', 'Leave'), ('TRAINING', 'Training')], max_length=30)),
                ('last_location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=40)),
                ('device_id', models.CharField(max_length=255)),
                ('fcm_token', models.TextField(blank=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('nationality', models.CharField(default='Nigeria', max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('PLATFORM_ADMIN', 'Platform Admin'), ('STATE_COMMANDER', 'State Commander'), ('LGA_COMMANDER', 'LGA Commander'), ('STATION_COMMANDER', 'Station Commander'), ('DISPATCHER', 'Dispatcher'), ('PATROL_SUPERVISOR', 'Patrol Supervisor'), ('PATROL_OFFICER', 'Patrol Officer'), ('RESPONDER', 'Responder'), ('ANALYST', 'Analyst'), ('CCTV_OPERATOR', 'CCTV Operator'), ('EMERGENCY_OPERATOR', 'Emergency Operator'), ('AGENCY_STAFF', 'Agency Staff'), ('CITIZEN', 'Citizen')], default='CITIZEN', max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('BLOCKED', 'Blocked'), ('DEACTIVATED', 'Deactivated')], default='PENDING', max_length=30)),
                ('verification_status', models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='UNVERIFIED', max_length=30)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('language', models.CharField(default='en', max_length=20)),
                ('timezone', models.CharField(default='Africa/Lagos', max_length=60)),
                ('dark_mode', models.BooleanField(default=False)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'ordering': ['first_name'],
            },
            managers=[
                ('objects', accounts.managers.UserManager()),
            ],
        ),
    ]
