# Generated by Django 6.0 on 2026-07-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnelassignment',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('PLATFORM_ADMIN', 'Platform Admin'), ('STATE_COMMANDER', 'State Commander'), ('LGA_COMMANDER', 'LGA Commander'), ('STATION_COMMANDER', 'Station Commander'), ('DISPATCHER', 'Dispatcher'), ('PATROL_SUPERVISOR', 'Patrol Supervisor'), ('PATROL_OFFICER', 'Patrol Officer'), ('RESPONDER', 'Responder'), ('ANALYST', 'Analyst'), ('AUDITOR', 'Auditor'), ('CCTV_OPERATOR', 'CCTV Operator'), ('EMERGENCY_OPERATOR', 'Emergency Operator'), ('AGENCY_STAFF', 'Agency Staff'), ('CITIZEN', 'Citizen')], max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('PLATFORM_ADMIN', 'Platform Admin'), ('STATE_COMMANDER', 'State Commander'), ('LGA_COMMANDER', 'LGA Commander'), ('STATION_COMMANDER', 'Station Commander'), ('DISPATCHER', 'Dispatcher'), ('PATROL_SUPERVISOR', 'Patrol Supervisor'), ('PATROL_OFFICER', 'Patrol Officer'), ('RESPONDER', 'Responder'), ('ANALYST', 'Analyst'), ('AUDITOR', 'Auditor'), ('CCTV_OPERATOR', 'CCTV Operator'), ('EMERGENCY_OPERATOR', 'Emergency Operator'), ('AGENCY_STAFF', 'Agency Staff'), ('CITIZEN', 'Citizen')], default='CITIZEN', max_length=40),
        ),
    ]
