# Generated by Django 5.2.14 on 2026-07-04 02:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeographyBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary_type', models.CharField(choices=[('state', 'State'), ('lga', 'LGA'), ('ward', 'Ward'), ('custom', 'Custom')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('state_name', models.CharField(blank=True, max_length=50, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['boundary_type'], name='geography_g_boundar_a3bfc0_idx')],
            },
        ),
    ]
