# Generated by Django 6.0 on 2026-07-01 02:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='geographyboundary',
            new_name='geography_g_boundar_a3bfc0_idx',
            old_name='geography_boundary_type_idx',
        ),
        migrations.AlterField(
            model_name='geographyboundary',
            name='boundary_type',
            field=models.CharField(choices=[('state', 'State'), ('lga', 'LGA'), ('ward', 'Ward'), ('custom', 'Custom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='geographyboundary',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(geography=True, srid=4326),
        ),
    ]
