# Generated by Django 5.2.14 on 2026-07-09 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10)),
                ('device_id', models.CharField(help_text='Unique device identifier', max_length=255, unique=True)),
                ('fcm_token', models.CharField(help_text='Firebase Cloud Messaging token', max_length=500)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('device_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used'],
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='mobile.mobiledevice')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mobiledevice',
            index=models.Index(fields=['user', 'is_active'], name='mobile_mobi_user_id_3920cd_idx'),
        ),
        migrations.AddIndex(
            model_name='mobiledevice',
            index=models.Index(fields=['fcm_token'], name='mobile_mobi_fcm_tok_b9539a_idx'),
        ),
        migrations.AddIndex(
            model_name='pushnotification',
            index=models.Index(fields=['recipient', '-created_at'], name='mobile_push_recipie_e21420_idx'),
        ),
        migrations.AddIndex(
            model_name='pushnotification',
            index=models.Index(fields=['status', '-created_at'], name='mobile_push_status_9acf80_idx'),
        ),
    ]
