# Generated by Django 5.2.14 on 2026-07-04 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='function',
            field=models.TextField(default='yes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='function_type',
            field=models.CharField(default='yes', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='ownership',
            field=models.CharField(default='yes', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='status',
            field=models.CharField(default='yes', max_length=100),
            preserve_default=False,
        ),
    ]
