# Generated by Django 5.2.14 on 2026-07-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='has_ambulance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
