# Generated by Django 5.2.14 on 2026-07-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_hospital_function_hospital_function_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='category',
            field=models.CharField(default='yes', max_length=100),
            preserve_default=False,
        ),
    ]
