# Generated by Django 6.0 on 2026-07-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='report_type',
            field=models.CharField(choices=[('crime', 'Crime'), ('violence', 'Violence'), ('fire', 'Fire'), ('flood', 'Flood'), ('accident', 'Accident'), ('Other', 'Other')], max_length=50),
        ),
    ]
