# Generated by Django 5.2.14 on 2026-07-16 09:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_incident_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='incidents/%d/%m/%Y/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
