# Generated by Django 6.0 on 2026-07-01 00:45

from django.db import migrations
import django.contrib.gis.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_fix_state_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='geometry',
            field=django.contrib.gis.db.models.fields.LineStringField(geography=True, srid=4326),
        ),
    ]