# Generated by Django 5.2.14 on 2026-05-15 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_rename_stateboundary_state_lga_delete_lgaboundary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reports',
            old_name='location',
            new_name='geometry',
        ),
    ]
