# Generated by Django 5.2.14 on 2026-05-15 10:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_rename_location_reports_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
