# Generated by Django 6.0 on 2026-07-01 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_incidentmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentmedia',
            name='file',
            field=models.FileField(upload_to='incidents/%d/%m/%Y/'),
        ),
    ]
