# Generated by Django 5.2.14 on 2026-05-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_state_geometry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lga',
            name='state',
        ),
    ]
