# Generated by Django 5.2.14 on 2026-05-15 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_remove_lga_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lgas', to='reports.state'),
        ),
    ]
