# Generated by Django 5.2.14 on 2026-05-15 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_lga_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reports',
            new_name='Incident',
        ),
    ]
