# Generated by Django 5.2.14 on 2026-07-09 10:50

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPSPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('heading', models.FloatField(default=0)),
                ('speed', models.FloatField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PatrolCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ARRIVED', 'Arrived'), ('DEPARTED', 'Departed'), ('MISSED', 'Missed')], default='PENDING', max_length=20)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatrolShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_type', models.CharField(choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('NIGHT', 'Night'), ('CUSTOM', 'Custom')], max_length=30)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatrolTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team_type', models.CharField(choices=[('RAPID_RESPONSE', 'Rapid Response'), ('HIGHWAY_PATROL', 'Highway Patrol'), ('TRAFFIC_CONTROL', 'Traffic Control'), ('INVESTIGATION', 'Investigation'), ('SWAT', 'SWAT'), ('MARINE', 'Marine Patrol'), ('DRONE', 'Drone Unit'), ('FIRE', 'Fire Response'), ('MEDICAL', 'Medical Response'), ('K9', 'K9 Unit')], max_length=40)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('DISPATCHED', 'Dispatched'), ('ON_PATROL', 'On Patrol'), ('OFFLINE', 'Offline'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('ON_PATROL', 'On Patrol'), ('MAINTENANCE', 'Maintenance'), ('OUT_OF_SERVICE', 'Out Of Service')], default='AVAILABLE', max_length=30)),
                ('tracker_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleFuelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litres', models.DecimalField(decimal_places=2, max_digits=8)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('odometer', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('description', models.TextField()),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('CAR', 'Car'), ('PICKUP', 'Pickup'), ('SUV', 'SUV'), ('MOTORCYCLE', 'Motorcycle'), ('AMBULANCE', 'Ambulance'), ('FIRE_TRUCK', 'Fire Truck'), ('BOAT', 'Boat'), ('DRONE', 'Drone'), ('HELICOPTER', 'Helicopter')], max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatrolEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('equipment_type', models.CharField(choices=[('RADIO', 'Radio'), ('BODY_CAMERA', 'Body Camera'), ('MEDICAL_KIT', 'Medical Kit'), ('FIRE_EXTINGUISHER', 'Fire Extinguisher'), ('FLASHLIGHT', 'Flashlight'), ('TABLET', 'Tablet'), ('DRONE_CONTROLLER', 'Drone Controller'), ('GPS_DEVICE', 'GPS Device'), ('OTHER', 'Other')], max_length=50)),
                ('serial_number', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost'), ('RETIRED', 'Retired')], default='AVAILABLE', max_length=30)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.agency')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.personnelassignment')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrol.patrolequipment')),
            ],
        ),
        migrations.CreateModel(
            name='PatrolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_team_lead', models.BooleanField(default=False)),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.personnelassignment')),
            ],
        ),
        migrations.CreateModel(
            name='PatrolMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('CRITICAL', 'Critical'), ('EMERGENCY', 'Emergency')], default='NORMAL', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En Route'), ('ARRIVED', 'Arrived'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='PENDING', max_length=30)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed'), ('ABORTED', 'Aborted')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('dispatch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patrol_mission', to='dispatch.dispatch')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
