# Generated by Django 5.2.14 on 2026-07-09 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('patrol', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patrolmission',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.incident'),
        ),
        migrations.AddField(
            model_name='patrolcheckpoint',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='patrol.patrolmission'),
        ),
        migrations.AddField(
            model_name='gpsposition',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_points', to='patrol.patrolmission'),
        ),
        migrations.AddField(
            model_name='patrolteam',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patrol_teams', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='patrolteam',
            name='commander',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commanded_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patrolshift',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrol.patrolteam'),
        ),
        migrations.AddField(
            model_name='patrolmission',
            name='patrol_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrol.patrolteam'),
        ),
        migrations.AddField(
            model_name='patrolmembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='patrol.patrolteam'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='accounts.agency'),
        ),
        migrations.AddField(
            model_name='gpsposition',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrol.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='patrol_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrol.patrolteam'),
        ),
        migrations.AddField(
            model_name='vehicleassignment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrol.vehicle'),
        ),
        migrations.AddField(
            model_name='patrolmission',
            name='vehicle_assignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='patrol.vehicleassignment'),
        ),
        migrations.AddField(
            model_name='vehiclefuellog',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrol.vehicle'),
        ),
        migrations.AddField(
            model_name='vehiclemaintenance',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patrol.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patrol.vehicletype'),
        ),
        migrations.AlterUniqueTogether(
            name='patrolmembership',
            unique_together={('team', 'personnel')},
        ),
    ]
