# Generated by Django 6.0 on 2026-06-30 23:41

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveillance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('road_type', models.CharField(choices=[('highway', 'Highway'), ('arterial', 'Arterial'), ('collector', 'Collector'), ('local', 'Local')], default='local', max_length=20)),
                ('geometry', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('speed_limit', models.IntegerField(help_text='Speed limit in km/h')),
                ('lanes', models.IntegerField(default=2)),
                ('capacity', models.IntegerField(help_text='Vehicles per hour')),
                ('is_monitored', models.BooleanField(default=True)),
                ('last_flow_update', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_monitored'], name='traffic_roa_is_moni_c8254f_idx'), models.Index(fields=['road_type'], name='traffic_roa_road_ty_356b94_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrafficCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(blank=True, help_text='e.g., Northbound', max_length=50)),
                ('vehicle_detection_enabled', models.BooleanField(default=True)),
                ('speed_detection_enabled', models.BooleanField(default=False)),
                ('daily_vehicle_count', models.IntegerField(default=0)),
                ('last_count_update', models.DateTimeField(auto_now=True)),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_data', to='surveillance.camera')),
                ('monitored_road', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic.road')),
            ],
            options={
                'ordering': ['camera__name'],
            },
        ),
        migrations.CreateModel(
            name='TrafficAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('congestion', 'Congestion Alert'), ('accident', 'Accident Detected'), ('abnormal_speed', 'Abnormal Speed'), ('road_closure', 'Road Closure'), ('weather', 'Weather Impact')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('road', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic.road')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type', '-created_at'], name='traffic_tra_alert_t_33a10f_idx'), models.Index(fields=['severity', '-created_at'], name='traffic_tra_severit_64b11d_idx'), models.Index(fields=['acknowledged'], name='traffic_tra_acknowl_11ed1a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrafficFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_count', models.IntegerField(default=0)),
                ('average_speed', models.FloatField(help_text='Average speed in km/h')),
                ('congestion_level', models.CharField(choices=[('free', 'Free Flow'), ('moderate', 'Moderate'), ('heavy', 'Heavy'), ('severe', 'Severe')], default='free', max_length=20)),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_flows', to='traffic.road')),
            ],
            options={
                'ordering': ['-measured_at'],
                'indexes': [models.Index(fields=['road', '-measured_at'], name='traffic_tra_road_id_47b16b_idx'), models.Index(fields=['congestion_level', '-measured_at'], name='traffic_tra_congest_4f895b_idx')],
            },
        ),
        migrations.CreateModel(
            name='TrafficIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('accident', 'Accident'), ('congestion', 'Congestion'), ('road_closure', 'Road Closure'), ('construction', 'Construction'), ('weather', 'Weather Related'), ('event', 'Special Event')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('monitoring', 'Monitoring')], default='active', max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('road_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('affected_lanes', models.IntegerField(default=1, help_text='Number of affected lanes')),
                ('estimated_duration', models.IntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_traffic_incidents', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_traffic_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
                'indexes': [models.Index(fields=['status', '-reported_at'], name='traffic_tra_status_158619_idx'), models.Index(fields=['severity', '-reported_at'], name='traffic_tra_severit_b58d91_idx'), models.Index(fields=['location'], name='traffic_tra_locatio_4087db_idx')],
            },
        ),
    ]
