# Generated by Django 5.2.14 on 2026-07-04 09:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='road',
            name='source_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='road',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='Vehicles per hour', null=True),
        ),
        migrations.AlterField(
            model_name='road',
            name='geometry',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='road',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='road',
            name='speed_limit',
            field=models.IntegerField(blank=True, help_text='Speed limit in km/h', null=True),
        ),
        migrations.AddIndex(
            model_name='road',
            index=models.Index(fields=['source_id'], name='traffic_roa_source__80364c_idx'),
        ),
    ]
