# Generated by Django 5.2.14 on 2026-07-09 10:50

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(help_text='Unique camera identifier', max_length=100, unique=True)),
                ('mac_address', models.CharField(blank=True, help_text='MAC address (e.g., 00:1A:2B:3C:4D:5E)', max_length=17, null=True, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('camera_type', models.CharField(choices=[('fixed', 'Fixed'), ('ptz', 'PTZ (Pan-Tilt-Zoom)'), ('dome', 'Dome'), ('bullet', 'Bullet'), ('thermal', 'Thermal')], default='fixed', max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(help_text='Camera GPS coordinates', srid=4326)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('port', models.IntegerField(default=80)),
                ('rtsp_url', models.URLField(blank=True, help_text='RTSP stream URL', max_length=500)),
                ('hls_url', models.URLField(blank=True, help_text='HLS stream URL', max_length=500)),
                ('username', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, help_text='Encrypted at rest', max_length=255)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('maintenance', 'Under Maintenance'), ('error', 'Error')], default='offline', max_length=20)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('last_offline', models.DateTimeField(blank=True, null=True)),
                ('coverage_radius', models.FloatField(default=100, help_text='Coverage radius in meters')),
                ('viewing_angle', models.FloatField(default=90, help_text='Viewing angle in degrees')),
                ('direction', models.FloatField(default=0, help_text='Direction in degrees (0 = North)')),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amotekun_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='stations.amotekunstation')),
                ('police_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='stations.policestation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CameraAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('motion', 'Motion Detected'), ('intrusion', 'Intrusion Detected'), ('object_left', 'Object Left Behind'), ('face_detected', 'Face Detected'), ('license_plate', 'License Plate Detected'), ('offline', 'Camera Offline'), ('error', 'Camera Error')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('message', models.TextField()),
                ('snapshot_path', models.CharField(blank=True, max_length=500)),
                ('video_path', models.CharField(blank=True, max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_camera_alerts', to=settings.AUTH_USER_MODEL)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='surveillance.camera')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_alerts', to='reports.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CameraRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('is_motion_detected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='surveillance.camera')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camera_recordings', to='reports.incident')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['camera_id'], name='surveillanc_camera__55df99_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['mac_address'], name='surveillanc_mac_add_87da9e_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['status'], name='surveillanc_status_d9ac95_idx'),
        ),
        migrations.AddIndex(
            model_name='camera',
            index=models.Index(fields=['location'], name='surveillanc_locatio_ced5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='cameraalert',
            index=models.Index(fields=['camera', '-created_at'], name='surveillanc_camera__8b6d59_idx'),
        ),
        migrations.AddIndex(
            model_name='cameraalert',
            index=models.Index(fields=['severity', '-created_at'], name='surveillanc_severit_8c962b_idx'),
        ),
        migrations.AddIndex(
            model_name='cameraalert',
            index=models.Index(fields=['acknowledged'], name='surveillanc_acknowl_39ebfe_idx'),
        ),
        migrations.AddIndex(
            model_name='camerarecording',
            index=models.Index(fields=['camera', '-start_time'], name='surveillanc_camera__6d76fd_idx'),
        ),
        migrations.AddIndex(
            model_name='camerarecording',
            index=models.Index(fields=['incident'], name='surveillanc_inciden_e5bdc4_idx'),
        ),
    ]
