# Generated by Django 5.2.14 on 2026-06-29 13:30

import surveillance.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='password',
            field=surveillance.fields.EncryptedCharField(blank=True),
        ),
        migrations.AlterField(
            model_name='camera',
            name='username',
            field=surveillance.fields.EncryptedCharField(blank=True),
        ),
    ]
