# Generated by Django 6.0 on 2026-06-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_4e3567_idx',
            old_name='notifications_recipient_is_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_created_ae6ed6_idx',
            old_name='notifications_created_at_idx',
        ),
    ]
